### ISSUE TITLE
[Feature] adding a random number generator

### ISSUE THREAD

**Issue by wojciechsobon** [warzocha/splitn#1]
A nice feature would be to add a random number generator of a certain length with the possibility of declaring an initial combination of numbers / digits. It should works as an integral and separate function of the splin.

Example:
generate random number with length 4 starts from 01 (or range) -> 0123, 0145, 0178 etc.

**Comment by warzocha** [comment]
@wojciechsobon it is now possible by using the `--pattern / -p` option. Look at examples below.
1. `splitn -p "01\d{2}"` outputs sequence of numbers beginning with "01" and ending with two randomly generated
2. `splitn abc -p "a .*"` outputs split sequences beginning with "a " ie. `a bc` and `a b c`, but not `ab c`

**Comment by wojciechsobon** [comment]
LGTM, thx!
